import { IPost } from '../shared/interfaces/post.interfaces';
export const postMock: IPost[] = [
  {
    title: 'Homoseksualizam',
    desc: 'lorem ipsum jebac',
    username: 'Pedał1',
    likes: ['we'],
    comments: 30,
    date: new Date(),
    subtitle: 'gejoza',
  },
  {
    title: 'Homoseksualizam5',
    desc: 'lorem ipsum jebac',
    username: 'Pedał5',
    likes: ['wronka', 'we'],
    comments: 30,
    date: new Date(),
    subtitle: 'gejoza2',
  },
  {
    title: 'Homoseksualizam4',
    desc: 'lorem ipsum jebac',
    username: 'Pedał4',
    likes: ['wronka', 'we'],
    comments: 30,
    date: new Date(),
    subtitle: 'gejoza3',
  },
  {
    title: 'Homoseksualizam3',
    desc: 'lorem ipsum jebac',
    username: 'Pedał3',
    likes: ['wronka', 'we'],
    comments: 30,
    date: new Date(),
    subtitle: 'gejoza4',
  },
  {
    title: 'Homoseksualizam2',
    desc: 'lorem ipsum jebac',
    username: 'Pedał2',
    likes: ['wronka', 'we'],
    comments: 30,
    date: new Date(),
    subtitle: 'gejoza5',
  },
];
